# Generated by Django 5.0.6 on 2024-05-28 08:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('managment', '0002_operator_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(20)])),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auther', to='managment.operator')),
            ],
        ),
    ]
