# Generated by Django 5.0.6 on 2024-06-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='send_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
