# Generated by Django 5.0.6 on 2024-05-28 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0002_operator_delete_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operator',
            old_name='phone',
            new_name='mobile',
        ),
    ]
